# permissions for end users to edit ats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: at-editor-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - ats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - ats/status
  verbs:
  - get
